[package]
name = "simple-json"
version = "0.1.6"
authors = ["Xiliang Chen<xlc>", "Jimmy Chu<jimmychu0807>"]
edition = "2018"

[dependencies]
paste = "0.1"
num-traits = { version = "0.2", default-features = false }

[features]
default = ["std"]
std = []
