[package]
name = "simple-json"
version = "0.1.5"
authors = [""]
edition = "2018"

[dependencies]
paste = "0.1"
num-traits = { version = "0.2", default-features = false }

[features]
default = ["std"]
std = []
